### ISSUE TITLE
gstreamer-1.0.mk invalid argument

### ISSUE THREAD

**Issue by ravikantojha** [justinjoy/gst-android-camera#10]
I have try all 4 floder to specify path for gstreamer-1.0.mk 
   gstreamser/(arm64,armv7,x86,x86_64,)/share/gst-android/ndk-build/gstreamer-1.0.mk: Invalid argument
make: *** No rule to make target ':/gstreamser/(same folder)/share/gst-android/ndk-build/gstreamer-1.0.mk'.

android,mk file
#
# Copyright (C) 2012, Collabora Ltd.
#   Author: Youness Alaoui
#
# Copyright (C) 2016-2017, Collabora Ltd.
#   Author: Justin Kim <justin.kim@collabora.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation
# version 2.1 of the License.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301 USA

LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

#LOCAL_CFLAGS := -DGST_USE_UNSTABLE_API
#LOCAL_MODULE    := android_camera
#LOCAL_SRC_FILES := android_camera.c
#LOCAL_STATIC_LIBRARIES := gstreamer_android
#LOCAL_LDLIBS := -landroid -llog -lcamera2ndk -lmediandk

LOCAL_MODULE    := android_camera
LOCAL_SRC_FILES := android_camera.c
include $(BUILD_SHARED_LIBRARY)

ifeq ($(TARGET_ARCH_ABI),armeabi)
GSTREAMER_ROOT        := $F:/gstreamser/arm
else ifeq ($(TARGET_ARCH_ABI),armeabi-v7a)
GSTREAMER_ROOT        := $F:/gstreamser/armv7
else ifeq ($(TARGET_ARCH_ABI),arm64-v8a)
GSTREAMER_ROOT        := $F:/gstreamser/arm64
else ifeq ($(TARGET_ARCH_ABI),x86)
GSTREAMER_ROOT        := $F:/gstreamser/x86
else ifeq ($(TARGET_ARCH_ABI),x86_64)
GSTREAMER_ROOT        := $F:/gstreamser/x86_64
else
$(error Target arch ABI not supported: $(TARGET_ARCH_ABI))
endif

GSTREAMER_NDK_BUILD_PATH  := $F:/gstreamser/x86_64/share/gst-android/ndk-build

include $(GSTREAMER_NDK_BUILD_PATH)/plugins.mk
GSTREAMER_PLUGINS	:=  $(GSTREAMER_PLUGINS_CORE) \
			    $(GSTREAMER_PLUGINS_PLAYBACK) \
			    $(GSTREAMER_PLUGINS_CODECS) \
			    opengl

include $(GSTREAMER_NDK_BUILD_PATH)/gstreamer-1.0.mk

Please help thanks in adavance

**Comment by justinjoy** [comment]
hi @ravikantojha 
it's difficult to reproduce your error. Could you please give me more detailed information listed below?
 * GStreamer SDK version
 * NDK version
 * OS
 * Application that you want to build

**Comment by ravikantojha** [comment]
Thanks for replying sir


   - GStreamer SDK version: 1.16.2
   - NDK version: 21.2.6472646
   - OS :windows
   - Application that you want to build:gst-android- camera

**Comment by justinjoy** [comment]
>    - NDK version: 21.2.6472646

Your NDK version is too high to use the SDK.
Note that GStreamer recommends NDK r1.18b if GStreamer version is 1.16.

>    - OS :windows

And, I am not sure if the SDK for Android supports windows. I think they are tested only on Linux and Mac OSX.

**Comment by ravikantojha** [comment]
Hi sir
Error is solve but new error is show
gst.h file not found

GStreamer version is 1.16.and also try  1.12.1

**Comment by justinjoy** [comment]
@ravikantojha sorry, but it's hard to solve because of a lack of information.
Can you attach the entire build log?

**Comment by ravikantojha** [comment]
Hi Sir.
Thanks for reply, I have attached a complete build log please find
attachment.
*Name Ravikant ojha*
*Mob. No. 9098538764*

**Comment by ravikantojha** [comment]
Build command failed.
Error while executing process C:\Users\ravik\AppData\Local\Android\Sdk\ndk\18.1.5063045\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\ravik\gst-android-camera\app\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\Users\ravik\gst-android-camera\app\src\main\jni\Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-19 NDK_OUT=C:/Users/ravik/gst-android-camera/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\ravik\gst-android-camera\app\build\intermediates\ndkBuild\debug\lib NDK_APPLICATION_MK=src/main/jni/Application.mk GSTREAMER_JAVA_SRC_DIR=src/main/java GSTREAMER_ROOT_ANDROID=/F/gstreamser/ GSTREAMER_ASSETS_DIR=src/main/assets APP_PLATFORM=android-24 android_camera gstreamer_android}
[arm64-v8a] Compile        : android_camera <= android_camera.c

C:/Users/ravik/gst-android-camera/app/src/main/jni/android_camera.c:29:10: fatal error: 'gst/gst.h' file not found
#include <gst/gst.h>
         ^~~~~~~~~~~
1 error generated.
make: *** [C:/Users/ravik/gst-android-camera/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs-debug/android_camera/android_camera.o] Error 1

**Comment by ravikantojha** [comment]
Build command failed.
Error while executing process C:\Users\ravik\AppData\Local\Android\Sdk\ndk\18.1.5063045\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\ravik\gst-android-camera\app\src\main\jni\Android.mk NDK_APPLICATION_MK=C:\Users\ravik\gst-android-camera\app\src\main\jni\Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-19 NDK_OUT=C:/Users/ravik/gst-android-camera/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\ravik\gst-android-camera\app\build\intermediates\ndkBuild\debug\lib NDK_APPLICATION_MK=src/main/jni/Application.mk GSTREAMER_JAVA_SRC_DIR=src/main/java GSTREAMER_ROOT_ANDROID=/F/gstreamser/ GSTREAMER_ASSETS_DIR=src/main/assets APP_PLATFORM=android-24 android_camera gstreamer_android}
[arm64-v8a] Compile        : android_camera <= android_camera.c

C:/Users/ravik/gst-android-camera/app/src/main/jni/android_camera.c:29:10: fatal error: 'gst/gst.h' file not found
#include <gst/gst.h>
         ^~~~~~~~~~~
1 error generated.
make: *** [C:/Users/ravik/gst-android-camera/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs-debug/android_camera/android_camera.o] Error 1

**Comment by justinjoy** [comment]
> GSTREAMER_ROOT_ANDROID=/F/gstreamser/ 

It seems that you set the wrong path for `GSTREAMER_ROOT_ANDROID`.
Shouldn't it start with `F:` ?

**Comment by ravikantojha** [comment]
Hi sir,
Thanks for replying,
F is a drive location where gstream SDK path.
Please let me know how to set

GSTREAMER_ROOT_ANDROID path

**Comment by justinjoy** [comment]
> Hi sir, Thanks for replying, F is a drive location where gstream SDK path. Please let me know how to set GSTREAMER_ROOT_ANDROID path

Please read GStreamer document or instruction of application carefully.
I also mentioned it in README file. 
Refer to https://github.com/justinjoy/gst-android-camera#build-and-installation
