### ISSUE TITLE
ahcsrc & front camera

### ISSUE THREAD

**Issue by the-information-guy** [justinjoy/gst-android-camera#3]
Is it possible to access the front camera with `ahcsrc` ? If so, how ?

Thanks

**Comment by justinjoy** [comment]
You can set `device` property, but it is device dependent value. I assume `1` would be the front? not sure.

**Comment by the-information-guy** [comment]
Thanks, was looking for the properties. 

If some people are also looking for'em, there they are : https://github.com/GStreamer/gst-plugins-bad/blob/master/sys/androidmedia/gstahcsrc.c :)

**Comment by QiaoJingjing** [comment]
How do I set this parameter? @the-information-guy 
thanks
