### ISSUE TITLE
Continuous video focus mode

### ISSUE THREAD

**Issue by the-information-guy** [justinjoy/gst-android-camera#4]
Hey,

I am trying to set the continuous video focus mode (autofocus) on `ahcsrc` 

So far, can't get it working with each of the following : 

```
g_object_set (ahc->ahcsrc, GST_PHOTOGRAPHY_PROP_FOCUS_MODE, 7, NULL);
g_object_set (ahc->ahcsrc, GST_PHOTOGRAPHY_PROP_FOCUS_MODE, GST_PHOTOGRAPHY_FOCUS_MODE_CONTINUOUS_EXTENDED, NULL);
```
Any idea ? :)

Thanks

**Comment by justinjoy** [comment]
The feature is mapped to [FOCUS_MODE_CONTINUOUS_VIDEO](https://developer.android.com/reference/android/hardware/Camera.Parameters.html#FOCUS_MODE_CONTINUOUS_VIDEO). According to the API doc, if autofocus is enabled, the focus is locked.

Did you check whether it works if auto focus is cancelled before calling it?
You might need to call `gst_photography_set_autofocus` with `FALSE` to cancel autofocus.

**Comment by justinjoy** [comment]
If it doesn't work even after cancelling auto focus, please file a bug on [bugzilla](https://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer).

**Comment by the-information-guy** [comment]
Assuming `ahc->ahcsrc` is the `GstPhotography*` element used as param in the `set_autofocus `method : 

```
gst_photography_set_autofocus(ahc->ahcsrc, FALSE);
g_object_set(ahc->ahcsrc, GST_PHOTOGRAPHY_PROP_FOCUS_MODE, GST_PHOTOGRAPHY_FOCUS_MODE_CONTINUOUS_EXTENDED, NULL);
```

That is still not auto focusing by itself

**Comment by justinjoy** [comment]
@the-information-guy 
Please, check 56df844c09a5f1495cfc670f7b96cc3f701f1245 :)

**Comment by the-information-guy** [comment]
Thanks 👍
