### ISSUE TITLE
Remove personal path

### ISSUE THREAD

**Issue by wf9a5m75** [justinjoy/gst-android-camera#5]
Should not include personal path.

https://github.com/justinjoy/gst-android-camera/blob/5e092d5dda188741876ff1764baa62c781065fd2/gradle.properties#L18

Thank you for creating this example, by the way.

**Comment by justinjoy** [comment]
Yes, it shouldn't be there, but `gstAndroidRoot` must be defined.
Maybe, we need  some comments to notify this matter to user.

**Comment by wf9a5m75** [comment]
Year, written in the README.md is enough I think.

-------

I have just started to lean gstreamer, but my goal is creating own plugin for my android project.
I already did [Android Tutorials](https://gstreamer.freedesktop.org/documentation/tutorials/android/index.html), but I'm not sure what I should do next.

Is there any good examples to learn how to create own gstreamer plugin (such as displaying  `hello world` on surface view from plugin side)?

**Comment by justinjoy** [comment]
hmm, making a plugin is not difficult. [Plugin writer's guide](https://gstreamer.freedesktop.org/documentation/plugin-development/index.html
) would be a starting point for you.

But I am not sure you can make your own plugin in a simple way to display 'hello world' on surface. As you can see in my example, it uses `glimagesink` which is one of the most complex plugin.

**Comment by wf9a5m75** [comment]
Umm, ok. I will try the guide pages at once.
